theme: jekyll-theme-cayman

# Setup
title:        雲霏霏的博客
tagline:      不积跬步，无以至千里。
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       yunfeifei
  url:        http://yunfeifei.github.io

# Gems
gems:
  - jekyll-paginate