theme: jekyll-theme-cayman

# Setup
title:        雲霏霏的博客
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       雲霏霏
  url:        http://yunfeifei.github.io

# Gems
gems:
  - jekyll-paginate